### ISSUE TITLE
Перестала работать отправка сообщений

### ISSUE THREAD

**Issue by sergey-zero** [UltraShock98/vk-io#3]
В версии 2.0.7 работал следующий код
`vk.api.messages.send({user_id: 1, message: "test3", guid: Math.random()});`
Сейчас даёт ошибку

> Unhandled rejection (<{"id":100,"msg":"One of the parameters...>, no stack trace)

**Comment by UltraShock98** [comment]
Guid больше не нужен, я в обновление уже поправил. Сейчас используется random_id и заполняется Date.now(). Так что можно его убрать, актуальная версия 2.0.9 желательно обновится.
